import numpy
matrix1=numpy.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2=numpy.matrix([[0,1,7],[2,4,3],[5,6,9]])
print(matrix1)
print(matrix2)
matrix3=numpy.add(matrix1,matrix2)
print("ADDITION")
print(matrix3)
matrix3=numpy.subtract(matrix1,matrix2)
print("SUBTRACTION")
print(matrix3)
matrix3=numpy.multiply(matrix1,matrix2)
print("MULTIPLICATION")
print(matrix3)
matrix1=2*matrix1
print("SCALAR MULTI")
print(matrix1)
matrix1=numpy.transpose(matrix1)
print("TRANSPOSE")
print(matrix1) 
