import numpy
matrix1=numpy.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2=numpy.matrix([[1,2,5],[4,5,3],[7,8,9]])
matrix3=numpy.subtract(matrix1,matrix2)
matrix4=numpy.add(matrix1,matrix2)
matrix5=numpy.multiply(matrix1,matrix2)
print("SUBTRACT")
print(matrix3)
print("ADDITION")
print(matrix4)
print("MULTIPLICATION")
print(matrix5)
