import numpy
matrix1=numpy.matrix([[1,2,3],[3,4,5],[5,4,8]])
matrix2=numpy.matrix([[4,3,6],[8,2,1],[1,4,5]])
print("MATRIX A:")
print(matrix1)
print("")
print("MATRIX B:")
print(matrix2)
matrix3=numpy.add(matrix1,matrix2)
print("")
print("SUM :")
print(matrix3)
matrix4=numpy.subtract(matrix1,matrix2)
print("")
print("DIFFERENCE :")
print(matrix4)
matrix5=numpy.matmul(matrix1,matrix2)
print("")
print("PRODUCT :")
print(matrix5)
matrix6=2*matrix1
print("")
print("SCALAR MULTIPLICATION :")
print(matrix6)
matrix7=numpy.transpose(matrix1)
print("")
print("TRANSPOSE OF A :")
print(matrix7)
